<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NBCUWFD-819597" name="sat.test.automation.scripts.ScriptRunner" tests="1" failures="1" timestamp="26 Apr 2017 13:08:09 GMT" time="488.407" errors="0">
  <testcase name="run" time="488.407" classname="sat.test.automation.scripts.ScriptRunner">
    <failure type="java.lang.AssertionError" message="Error while performating action Click for the field PropertyClick on the AgencyGateway screen">
      <![CDATA[java.lang.AssertionError: Error while performating action Click for the field PropertyClick on the AgencyGateway screen
	at org.testng.Assert.fail(Assert.java:83)
	at sat.test.automation.core.SuperScript.actionDriver(SuperScript.java:2112)
	at sat.test.automation.scripts.BaseScriptRunner.executeTestData(BaseScriptRunner.java:48)
	at sat.test.automation.scripts.ScriptRunner.run(ScriptRunner.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.lang.NullPointerException
	at sat.test.automation.core.SuperScript.actionDriver(SuperScript.java:808)
	... 26 more
]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- sat.test.automation.scripts.ScriptRunner -->
